default_stages: [commit, manual]
repos:
  - repo: local
    hooks:
      - id: isort
        name: sort-imports
        entry: python -m
        args:
          - isort
        language: system
        types: [python]

  - repo: local
    hooks:
      - id: black
        name: format-code
        entry: python -m
        args:
          - black
        language: system
        types: [python]

  - repo: local
    hooks:
      - id: flake8
        name: lint-code
        entry: python -m
        args:
          - flake8
        language: system
        types: [python]
